// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbM7P9nODagGOG4asPRZQykvIJqbPXxgo',
    appId: '1:51368102398:web:ad6d768eaee2b327ee18af',
    messagingSenderId: '51368102398',
    projectId: 'quizbuilder-cd234',
    authDomain: 'quizbuilder-cd234.firebaseapp.com',
    storageBucket: 'quizbuilder-cd234.appspot.com',
    measurementId: 'G-X1S3SSSPWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpX-xmF3p2naM3eCzA-rLQG1rkSfg0GuA',
    appId: '1:51368102398:android:a5c923313a2c5e7cee18af',
    messagingSenderId: '51368102398',
    projectId: 'quizbuilder-cd234',
    storageBucket: 'quizbuilder-cd234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQWJH9xRZHiXfvDwKzUIlLpk02Xkng14',
    appId: '1:51368102398:ios:11c3474c12dd2a97ee18af',
    messagingSenderId: '51368102398',
    projectId: 'quizbuilder-cd234',
    storageBucket: 'quizbuilder-cd234.appspot.com',
    iosClientId: '51368102398-kedtdatj1au1h6490ijk6tntdt11puk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizbuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQWJH9xRZHiXfvDwKzUIlLpk02Xkng14',
    appId: '1:51368102398:ios:11c3474c12dd2a97ee18af',
    messagingSenderId: '51368102398',
    projectId: 'quizbuilder-cd234',
    storageBucket: 'quizbuilder-cd234.appspot.com',
    iosClientId: '51368102398-kedtdatj1au1h6490ijk6tntdt11puk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizbuilder',
  );
}
